# SwiftLint Configuration for Camera App
# https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - Camera
  - CameraTests
  - CameraUITests

excluded:
  - Pods
  - .build
  - DerivedData

# Rules configuration
disabled_rules:
  - todo # Allow TODO comments for development
  - trailing_whitespace # Sometimes needed for formatting

opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rules for camera app
custom_rules:
  # Prevent force unwrapping in production code
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: '!\s*$'
    match_kinds:
      - comment
    message: "Avoid force unwrapping in production code"
    severity: warning

# Line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# File length
file_length:
  warning: 500
  error: 1000

# Function length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Identifier names
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - api
    - ui
    - av
    - ci

# Type names
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Trailing newline
trailing_newline:
  ignores_empty_lines: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Empty count
empty_count:
  only_after_dot: true

# Force try
force_try:
  severity: error

# Force cast
force_cast:
  severity: error

# Implicitly unwrapped optional
implicitly_unwrapped_optional:
  severity: warning

# Legacy constructor
legacy_constructor:
  severity: warning

# Legacy constant
legacy_constant:
  severity: warning

# Legacy hsb
legacy_hsb:
  severity: warning

# Legacy random
legacy_random:
  severity: warning

# Notification center detach
notification_center_detach:
  severity: warning

# NSObject prelude
nsobject_prelude:
  severity: warning

# Override in extension
override_in_extension:
  severity: warning

# Prohibited interface builder
prohibited_interface_builder:
  severity: warning

# Prohibited super
prohibited_super:
  severity: warning

# Redundant objc attribute
redundant_objc_attribute:
  severity: warning

# Single test class
single_test_class:
  severity: warning

# Switch case on newline
switch_case_on_newline:
  severity: warning

# Unused closure parameter
unused_closure_parameter:
  severity: warning

# Unused control flow label
unused_control_flow_label:
  severity: warning

# Unused declaration
unused_declaration:
  severity: warning

# Unused import
unused_import:
  severity: warning

# Unused optional binding
unused_optional_binding:
  severity: warning

# Unused private declaration
unused_private_declaration:
  severity: warning

# Valid ibinspectable
valid_ibinspectable:
  severity: warning

# Xctest specific matcher
xct_specific_matcher:
  severity: warning
