name: Feature Request
description: Suggest a new feature or enhancement for the Camera App
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case and benefits of this feature.
      placeholder: "How would this feature help users?"
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - Video Recording
        - Teleprompter
        - Video Filters
        - Camera Controls
        - UI/UX
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If you have mockups, examples, or references, please share them.
      placeholder: "Drag and drop images or provide links..."

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details or considerations you're aware of.
      placeholder: "Any technical information that might be helpful..."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, I agree to follow the project's Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
